/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airbnb;

import java.awt.Color;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author tugrul
 */
public class register_page extends javax.swing.JFrame {

    String user_name;
    String email;
    String hashedPassword;

    /**
     * Creates new form register_page
     */
    public register_page() {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        register_main_label = new javax.swing.JLabel();
        username_rg_label = new javax.swing.JLabel();
        pass_rg_label = new javax.swing.JLabel();
        conf_pass_rg_label = new javax.swing.JLabel();
        email_rg_label = new javax.swing.JLabel();
        username_rg_tx = new javax.swing.JTextField();
        email_rg_tx = new javax.swing.JTextField();
        pass_rg_pf = new javax.swing.JPasswordField();
        conf_pass_rg_pf = new javax.swing.JPasswordField();
        sign_up_button = new javax.swing.JButton();
        go_back_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        register_main_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        register_main_label.setText("REGISTER");

        username_rg_label.setText("Username:");

        pass_rg_label.setText("Password (6 or more characters):");

        conf_pass_rg_label.setText("Confirm Password:");

        email_rg_label.setText("E-mail:");

        sign_up_button.setText("SIGN UP");
        sign_up_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sign_up_buttonActionPerformed(evt);
            }
        });

        go_back_button.setText("GO BACK");
        go_back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                go_back_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sign_up_button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(go_back_button))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(email_rg_label)
                                    .addComponent(username_rg_label)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(pass_rg_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(username_rg_tx)
                                        .addComponent(email_rg_tx)
                                        .addComponent(pass_rg_pf)
                                        .addComponent(conf_pass_rg_pf)
                                        .addComponent(conf_pass_rg_label)))))
                        .addGap(0, 36, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(register_main_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(register_main_label)
                .addGap(18, 18, 18)
                .addComponent(username_rg_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username_rg_tx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(email_rg_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(email_rg_tx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pass_rg_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pass_rg_pf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(conf_pass_rg_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(conf_pass_rg_pf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sign_up_button)
                    .addComponent(go_back_button))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void go_back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_go_back_buttonActionPerformed
        login_page e = new login_page();
        e.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_go_back_buttonActionPerformed

    private void sign_up_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sign_up_buttonActionPerformed
        PreparedStatement ps;
        ResultSet rs;

        String query = "INSERT INTO `Users` (`user_name`, `user_email`, `user_password`) VALUES (?,?,?)";
        try {
            if (validateData()) {
                ps = JDBC.getConnection().prepareStatement(query);

                ps.setString(1, user_name);
                ps.setString(2, email);
                ps.setString(3, hashedPassword);
                int action = ps.executeUpdate();
                if (action != 0) {
                    JOptionPane.showMessageDialog(null, "Registration completed.", "Success", 2);
                    login_page lp = new login_page();
                    lp.setVisible(true);
                    lp.setLocationRelativeTo(null);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "ERROR");
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(register_page.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_sign_up_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register_page().setVisible(true);

            }
        });

    }

    public boolean validateData() {
        if (username_rg_tx.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter your Username");
            username_rg_tx.requestFocusInWindow();
            return false;
        } 
        if (email_rg_tx.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter your Email");
            email_rg_tx.requestFocusInWindow();
            return false;
        } 
        if(String.valueOf(pass_rg_pf.getPassword()).equals("")){
            JOptionPane.showMessageDialog(null, "Please enter your Password");
            email_rg_tx.requestFocusInWindow();
            return false;
        }
        if(String.valueOf(conf_pass_rg_pf.getPassword()).equals("")){
            JOptionPane.showMessageDialog(null, "Please confirm your Password");
            email_rg_tx.requestFocusInWindow();
            return false;
        }
        if(!String.valueOf(pass_rg_pf.getPassword()).equals(String.valueOf(conf_pass_rg_pf.getPassword()))){
            JOptionPane.showMessageDialog(null, "Password doesn't match");
            email_rg_tx.requestFocusInWindow();
            return false;
        }
        else {
            user_name = username_rg_tx.getText();
            String password = String.valueOf(pass_rg_pf.getPassword());
            email = email_rg_tx.getText();
            hashedPassword = BCrypt.hashpw(password, BCrypt.gensalt());
            return true;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel conf_pass_rg_label;
    private javax.swing.JPasswordField conf_pass_rg_pf;
    private javax.swing.JLabel email_rg_label;
    private javax.swing.JTextField email_rg_tx;
    private javax.swing.JButton go_back_button;
    private javax.swing.JLabel pass_rg_label;
    private javax.swing.JPasswordField pass_rg_pf;
    private javax.swing.JLabel register_main_label;
    private javax.swing.JButton sign_up_button;
    private javax.swing.JLabel username_rg_label;
    private javax.swing.JTextField username_rg_tx;
    // End of variables declaration//GEN-END:variables
}
